# Generated by Django 5.0.7 on 2024-07-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_about_us_alter_blog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='about_us',
        ),
    ]
