# Generated by Django 5.0.7 on 2024-07-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_aboutus_delete_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('link', models.URLField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'about_us'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_us',
            field=models.TextField(max_length=500),
        ),
    ]
