# Generated by Django 5.0.7 on 2024-07-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_social_links_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_links',
            new_name='Social_link',
        ),
    ]
